// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw6YSwese3zNzkW_Ev6sU126VPgRle5mE',
    appId: '1:97111363348:web:705e075917dd93bdb23c01',
    messagingSenderId: '97111363348',
    projectId: 'smart-expense-manager-2253e',
    authDomain: 'smart-expense-manager-2253e.firebaseapp.com',
    storageBucket: 'smart-expense-manager-2253e.firebasestorage.app',
    measurementId: 'G-1X1TWVGP6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBdwh8pJoCXb0LbVREo12ux5JJ6gpDAZg',
    appId: '1:97111363348:android:b16da87f22763254b23c01',
    messagingSenderId: '97111363348',
    projectId: 'smart-expense-manager-2253e',
    storageBucket: 'smart-expense-manager-2253e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcNmcbqwVXDUx2DEHkCrQmo4OtpfNYEgw',
    appId: '1:97111363348:ios:5b544acbbe8ac813b23c01',
    messagingSenderId: '97111363348',
    projectId: 'smart-expense-manager-2253e',
    storageBucket: 'smart-expense-manager-2253e.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw6YSwese3zNzkW_Ev6sU126VPgRle5mE',
    appId: '1:97111363348:web:42264260e9ec6643b23c01',
    messagingSenderId: '97111363348',
    projectId: 'smart-expense-manager-2253e',
    authDomain: 'smart-expense-manager-2253e.firebaseapp.com',
    storageBucket: 'smart-expense-manager-2253e.firebasestorage.app',
    measurementId: 'G-Q046NG7R34',
  );
}
